config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create, :index, :show]
  end
  root to: 'restaurants#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, :dependent => :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian),
    message: "%{value} is not a valid category" }
  end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1,2,3,4,5], allow_nil: false,
   message: "%{value} is not a valid rating" }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new

  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.create(review_params)
    @restaurant.reviews << @review
    @restaurant.save
    redirect_to restaurant_reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |a| %>
<%= a.label :name %>
<%= a.text_field :name %>
<%= a.label :address %>
<%= a.text_field :address %>
<%= a.label :phonenumber %>
<%= a.text_field :phone_number %>
<%= a.label :category %>
<%= a.text_field :category %>
<%= a.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1> This is a list of all the Restaurant!</h1>


<% @restaurants.each do |restaurant| %>
<ul>
  <li id='restaurant' class='restaurant-box'>
    <h2><%= restaurant.name %></h2>
    <td><%= restaurant.address %></td>
    <td><%= restaurant.phone_number %></td>
    <td><%= restaurant.category %></td>
    <td><%= link_to "- Reviews", restaurant_reviews_path(restaurant) %></td>
    <td><%= link_to "- Show", restaurant %></td>
    <td><%= link_to "- Edit", edit_restaurant_path(restaurant) %></td>
    <td><%= link_to "- Delete restaurant", restaurant, method: :delete, data: { confirm: "Do you really want to delete this Restaurant?" } %></td>
  </li>
</ul>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>

<td><%= link_to "- Reviews", restaurant_reviews_path(@restaurant) %></td>

<%= form_for [@restaurant, @review] do |a| %>
<%= a.label :content %>
<%= a.text_field :content %>
<%= a.label :rating %>
<%= a.number_field :rating %>
<%= a.submit %>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review] do |a| %>
<%= a.label :content %>
<%= a.text_field :content %>
<%= a.label :rating %>
<%= a.number_field :rating %>
<%= a.submit %>
<% end %>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/index.html.erb
<h1> This is a list of all the reviews!</h1>

<%= link_to 'Create a review', new_restaurant_review_path(@restaurant) %>
<% @reviews.each do |review| %>
<ul>
  <li id='review' class='review-box'>
    <h2><%= review.content %></h2>
    <td><%= review.rating %></td>
    <td><%= link_to "- Show", restaurant_review_path(@restaurant, review) %></td>
  </li>
</ul>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<h1><%= @review.content %></h1>
<p><%= @review.rating %></p>